sudo: required
language: generic

services:
  - docker

after_success:
  - docker build -t bongster228/docker-deploy-client ./client
  - docker build -t bongster228/docker-deploy-nginx ./nginx
  - docker build -t bongster228/docker-deploy-api ./api
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin

  - docker push bongster228/docker-deploy-client
  - docker push bongster228/docker-deploy-nginx
  - docker push bongster228/docker-deploy-api

deploy:
  provider: elasticbeanstalk
  region: us-west-1
  app: docker-learn
  env: DockerLearn-env
  bucket_name: elasticbeanstalk-us-west-1-278374142069
  bucket_path: docker-deploy
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY
